spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/email_microservice
    username: postgres
    password: Ashish123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000



